/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Mon Aug 12 12:03:33 2019. */

#include "Recipe.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Options_fields[6] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, Options, size, size, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, Options, roomness, size, 0),
    PB_FIELD(  3, UENUM   , REQUIRED, STATIC  , OTHER, Options, boldness, roomness, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, Options, grinder, boldness, 0),
    PB_FIELD(  5, UENUM   , REQUIRED, STATIC  , OTHER, Options, temp, grinder, 0),
    PB_LAST_FIELD
};

const pb_field_t HourlyStats_fields[7] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, HourlyStats, product_used_ml, product_used_ml, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, HourlyStats, tank_weight_grams, product_used_ml, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, HourlyStats, clean_status, tank_weight_grams, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, HourlyStats, pressure_drop_psi, clean_status, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, HourlyStats, cabinet_temp_c, pressure_drop_psi, 0),
    PB_FIELD(  6, UINT32  , REQUIRED, STATIC  , OTHER, HourlyStats, unix_timestamp, cabinet_temp_c, 0),
    PB_LAST_FIELD
};

const pb_field_t MachineStatistics_fields[20] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, MachineStatistics, bootup_count, bootup_count, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, MachineStatistics, brew_clean_count, bootup_count, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, MachineStatistics, milk_clean_count, brew_clean_count, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, MachineStatistics, last_brew_clean_unix, milk_clean_count, 0),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, MachineStatistics, last_milk_clean_unix, last_brew_clean_unix, 0),
    PB_FIELD(  6, UINT32  , REQUIRED, STATIC  , OTHER, MachineStatistics, drinks_since_pm, last_milk_clean_unix, 0),
    PB_FIELD(  7, UINT32  , REQUIRED, STATIC  , OTHER, MachineStatistics, drinks_since_bin_clean, drinks_since_pm, 0),
    PB_FIELD(  8, UINT32  , REQUIRED, STATIC  , OTHER, MachineStatistics, drinks_since_brew_clean, drinks_since_bin_clean, 0),
    PB_FIELD(  9, BOOL    , REQUIRED, STATIC  , OTHER, MachineStatistics, setup_executed, drinks_since_brew_clean, 0),
    PB_FIELD( 10, UINT32  , REQUIRED, STATIC  , OTHER, MachineStatistics, last_pm_unix, setup_executed, 0),
    PB_FIELD( 11, FLOAT   , REQUIRED, STATIC  , OTHER, MachineStatistics, dispensed_coffee_grams, last_pm_unix, 0),
    PB_FIELD( 12, FLOAT   , REQUIRED, STATIC  , OTHER, MachineStatistics, dispensed_water_ml, dispensed_coffee_grams, 0),
    PB_FIELD( 13, UINT32  , REQUIRED, STATIC  , OTHER, MachineStatistics, total_drinks, dispensed_water_ml, 0),
    PB_FIELD( 14, UINT32  , REPEATED, STATIC  , OTHER, MachineStatistics, total_drinks_history, total_drinks, 0),
    PB_FIELD( 15, UINT32  , REQUIRED, STATIC  , OTHER, MachineStatistics, dispensed_coffee_since_bin_pull, total_drinks_history, 0),
    PB_FIELD( 17, FLOAT   , REQUIRED, STATIC  , OTHER, MachineStatistics, total_dispensed_ml, dispensed_coffee_since_bin_pull, 0),
    PB_FIELD( 18, FLOAT   , REQUIRED, STATIC  , OTHER, MachineStatistics, ml_since_clean, total_dispensed_ml, 0),
    PB_FIELD( 19, UINT32  , REQUIRED, STATIC  , OTHER, MachineStatistics, last_filter_unix, ml_since_clean, 0),
    PB_FIELD( 20, UINT32  , REQUIRED, STATIC  , OTHER, MachineStatistics, last_tower_unix, last_filter_unix, 0),
    PB_LAST_FIELD
};

const pb_field_t Statistics_fields[3] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, Statistics, machine_stats, machine_stats, &MachineStatistics_fields),
    PB_FIELD(  2, MESSAGE , REPEATED, STATIC  , OTHER, Statistics, drink_stats, machine_stats, &DrinkStatistics_fields),
    PB_LAST_FIELD
};

const pb_field_t DrinkStatistics_fields[6] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, DrinkStatistics, recipe_id, recipe_id, 0),
    PB_FIELD(  2, MESSAGE , REQUIRED, STATIC  , OTHER, DrinkStatistics, option, recipe_id, &Options_fields),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, DrinkStatistics, day_count, option, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, DrinkStatistics, total_count, day_count, 0),
    PB_FIELD(  5, UINT32  , REPEATED, STATIC  , OTHER, DrinkStatistics, total_count_history, total_count, 0),
    PB_LAST_FIELD
};

const pb_field_t Recipe_fields[4] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, Recipe, id, id, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, Recipe, name, id, 0),
    PB_FIELD(  4, MESSAGE , REPEATED, STATIC  , OTHER, Recipe, instructions, name, &Instruction_fields),
    PB_LAST_FIELD
};

const pb_field_t CoffeeParameters_fields[13] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, CoffeeParameters, temperature, temperature, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, CoffeeParameters, size, temperature, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, CoffeeParameters, grind_grams, size, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, CoffeeParameters, presoak_vol_ml, grind_grams, 0),
    PB_FIELD(  6, FLOAT   , REQUIRED, STATIC  , OTHER, CoffeeParameters, presoak_delay_ms, presoak_vol_ml, 0),
    PB_FIELD(  7, FLOAT   , REQUIRED, STATIC  , OTHER, CoffeeParameters, dwell_time_ms, presoak_delay_ms, 0),
    PB_FIELD(  8, FLOAT   , REQUIRED, STATIC  , OTHER, CoffeeParameters, hotbrew_vol_ml, dwell_time_ms, 0),
    PB_FIELD(  9, FLOAT   , REQUIRED, STATIC  , OTHER, CoffeeParameters, coldbrew_vol_ml, hotbrew_vol_ml, 0),
    PB_FIELD( 10, FLOAT   , REQUIRED, STATIC  , OTHER, CoffeeParameters, chamber_vol_percent, coldbrew_vol_ml, 0),
    PB_FIELD( 11, FLOAT   , REQUIRED, STATIC  , OTHER, CoffeeParameters, tank_temp_c, chamber_vol_percent, 0),
    PB_FIELD( 12, FLOAT   , REQUIRED, STATIC  , OTHER, CoffeeParameters, brew_psi, tank_temp_c, 0),
    PB_FIELD( 13, UINT32  , REQUIRED, STATIC  , OTHER, CoffeeParameters, bean_id, brew_psi, 0),
    PB_LAST_FIELD
};

const pb_field_t BeanInfo_fields[7] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, BeanInfo, name, name, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, BeanInfo, description, name, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, BeanInfo, caffeeine_level, description, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, BeanInfo, roast_level, caffeeine_level, 0),
    PB_FIELD(  5, STRING  , REQUIRED, STATIC  , OTHER, BeanInfo, color, roast_level, 0),
    PB_FIELD(  6, STRING  , REQUIRED, STATIC  , OTHER, BeanInfo, ui_name, color, 0),
    PB_LAST_FIELD
};

const pb_field_t OptionParameters_fields[5] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, OptionParameters, with_room_vol_percentage, with_room_vol_percentage, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, OptionParameters, extra_room_vol_percentage, with_room_vol_percentage, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, OptionParameters, bold_grams_percentage, extra_room_vol_percentage, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, OptionParameters, extra_bold_grams_percentage, bold_grams_percentage, 0),
    PB_LAST_FIELD
};

const pb_field_t DrinkTuneList_fields[4] = {
    PB_FIELD(  1, MESSAGE , REPEATED, STATIC  , FIRST, DrinkTuneList, coffee_params, coffee_params, &CoffeeParameters_fields),
    PB_FIELD(  4, STRING  , REQUIRED, STATIC  , OTHER, DrinkTuneList, name, coffee_params, 0),
    PB_FIELD(  5, MESSAGE , REPEATED, STATIC  , OTHER, DrinkTuneList, bean_infos, name, &BeanInfo_fields),
    PB_LAST_FIELD
};

const pb_field_t MilkParameters_fields[4] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, MilkParameters, cold_volume_ml, cold_volume_ml, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, MilkParameters, steamed_volume_ml, cold_volume_ml, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, MilkParameters, foamed_volume_ml, steamed_volume_ml, 0),
    PB_LAST_FIELD
};

const pb_field_t FlavorParameters_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, FlavorParameters, pump_num, pump_num, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, FlavorParameters, volume_ml, pump_num, 0),
    PB_LAST_FIELD
};

const pb_field_t PressureLUTVal_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, PressureLUTVal, time_ms, time_ms, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, PressureLUTVal, pressure_psi, time_ms, 0),
    PB_LAST_FIELD
};

const pb_field_t PressureLUT_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, PressureLUT, id, id, 0),
    PB_LAST_FIELD
};

const pb_field_t SetValveArg_fields[2] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, SetValveArg, valves_state, valves_state, 0),
    PB_LAST_FIELD
};

const pb_field_t LoopArg_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, LoopArg, loop_count, loop_count, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, LoopArg, end_loop_index, loop_count, 0),
    PB_LAST_FIELD
};

const pb_field_t WaitForArg_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, WaitForArg, conditions_bitmask, conditions_bitmask, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, WaitForArg, timeout_ms, conditions_bitmask, 0),
    PB_LAST_FIELD
};

const pb_field_t GrinderArg_fields[3] = {
    PB_FIELD(  1, ENUM    , REQUIRED, STATIC  , FIRST, GrinderArg, grinder, grinder, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, GrinderArg, grams, grinder, 0),
    PB_LAST_FIELD
};

const pb_field_t PumpArg_fields[5] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, PumpArg, hot_vol_ml, hot_vol_ml, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, PumpArg, cold_vol_ml, hot_vol_ml, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, PumpArg, pwm, cold_vol_ml, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, PumpArg, time_ms, pwm, 0),
    PB_LAST_FIELD
};

const pb_field_t PistonPwmArg_fields[3] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, PistonPwmArg, pwm, pwm, 0),
    PB_FIELD(  2, ENUM    , REQUIRED, STATIC  , OTHER, PistonPwmArg, direction, pwm, 0),
    PB_LAST_FIELD
};

const pb_field_t SweepArg_fields[3] = {
    PB_FIELD(  1, ENUM    , REQUIRED, STATIC  , FIRST, SweepArg, mode, mode, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, SweepArg, timeout_ms, mode, 0),
    PB_LAST_FIELD
};

const pb_field_t Instruction_fields[16] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, Instruction, inst_id, inst_id, 0),
    PB_ONEOF_FIELD(arguments,   3, UINT32  , ONEOF, STATIC  , OTHER, Instruction, arg_id, inst_id, 0),
    PB_ONEOF_FIELD(arguments,   4, FLOAT   , ONEOF, STATIC  , UNION, Instruction, piston_setpoint, inst_id, 0),
    PB_ONEOF_FIELD(arguments,   5, UINT32  , ONEOF, STATIC  , UNION, Instruction, valves_bitmask, inst_id, 0),
    PB_ONEOF_FIELD(arguments,   6, MESSAGE , ONEOF, STATIC  , UNION, Instruction, loop_args, inst_id, &LoopArg_fields),
    PB_ONEOF_FIELD(arguments,   7, MESSAGE , ONEOF, STATIC  , UNION, Instruction, grinder_args, inst_id, &GrinderArg_fields),
    PB_ONEOF_FIELD(arguments,   8, FLOAT   , ONEOF, STATIC  , UNION, Instruction, pwm, inst_id, 0),
    PB_ONEOF_FIELD(arguments,   9, UINT32  , ONEOF, STATIC  , UNION, Instruction, time_ms, inst_id, 0),
    PB_ONEOF_FIELD(arguments,  10, FLOAT   , ONEOF, STATIC  , UNION, Instruction, volume_ml, inst_id, 0),
    PB_ONEOF_FIELD(arguments,  11, MESSAGE , ONEOF, STATIC  , UNION, Instruction, wait_args, inst_id, &WaitForArg_fields),
    PB_ONEOF_FIELD(arguments,  12, MESSAGE , ONEOF, STATIC  , UNION, Instruction, pump_args, inst_id, &PumpArg_fields),
    PB_ONEOF_FIELD(arguments,  13, UINT32  , ONEOF, STATIC  , UNION, Instruction, no_arg, inst_id, 0),
    PB_ONEOF_FIELD(arguments,  14, MESSAGE , ONEOF, STATIC  , UNION, Instruction, piston_pwm_arg, inst_id, &PistonPwmArg_fields),
    PB_ONEOF_FIELD(arguments,  15, MESSAGE , ONEOF, STATIC  , UNION, Instruction, sweep_arg, inst_id, &SweepArg_fields),
    PB_ONEOF_FIELD(arguments,  16, FLOAT   , ONEOF, STATIC  , UNION, Instruction, degrees_c, inst_id, 0),
    PB_LAST_FIELD
};

const pb_field_t NutritionInfo_fields[11] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, NutritionInfo, ingredient_id, ingredient_id, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, NutritionInfo, calories, ingredient_id, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, NutritionInfo, sat_fat_mg, calories, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, NutritionInfo, trans_fat_mg, sat_fat_mg, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, NutritionInfo, sugar_mg, trans_fat_mg, 0),
    PB_FIELD(  6, FLOAT   , REQUIRED, STATIC  , OTHER, NutritionInfo, cholesterol_mg, sugar_mg, 0),
    PB_FIELD(  7, FLOAT   , REQUIRED, STATIC  , OTHER, NutritionInfo, sodium_mg, cholesterol_mg, 0),
    PB_FIELD(  8, FLOAT   , REQUIRED, STATIC  , OTHER, NutritionInfo, carb_mg, sodium_mg, 0),
    PB_FIELD(  9, FLOAT   , REQUIRED, STATIC  , OTHER, NutritionInfo, fiber_mg, carb_mg, 0),
    PB_FIELD( 10, FLOAT   , REQUIRED, STATIC  , OTHER, NutritionInfo, protein_mg, fiber_mg, 0),
    PB_LAST_FIELD
};










/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Statistics, machine_stats) < 65536 && pb_membersize(Statistics, drink_stats[0]) < 65536 && pb_membersize(DrinkStatistics, option) < 65536 && pb_membersize(Recipe, instructions[0]) < 65536 && pb_membersize(DrinkTuneList, coffee_params[0]) < 65536 && pb_membersize(DrinkTuneList, bean_infos[0]) < 65536 && pb_membersize(Instruction, arguments.loop_args) < 65536 && pb_membersize(Instruction, arguments.grinder_args) < 65536 && pb_membersize(Instruction, arguments.wait_args) < 65536 && pb_membersize(Instruction, arguments.pump_args) < 65536 && pb_membersize(Instruction, arguments.piston_pwm_arg) < 65536 && pb_membersize(Instruction, arguments.sweep_arg) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Options_HourlyStats_MachineStatistics_Statistics_DrinkStatistics_Recipe_CoffeeParameters_BeanInfo_OptionParameters_DrinkTuneList_MilkParameters_FlavorParameters_PressureLUTVal_PressureLUT_SetValveArg_LoopArg_WaitForArg_GrinderArg_PumpArg_PistonPwmArg_SweepArg_Instruction_NutritionInfo)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Statistics, machine_stats) < 256 && pb_membersize(Statistics, drink_stats[0]) < 256 && pb_membersize(DrinkStatistics, option) < 256 && pb_membersize(Recipe, instructions[0]) < 256 && pb_membersize(DrinkTuneList, coffee_params[0]) < 256 && pb_membersize(DrinkTuneList, bean_infos[0]) < 256 && pb_membersize(Instruction, arguments.loop_args) < 256 && pb_membersize(Instruction, arguments.grinder_args) < 256 && pb_membersize(Instruction, arguments.wait_args) < 256 && pb_membersize(Instruction, arguments.pump_args) < 256 && pb_membersize(Instruction, arguments.piston_pwm_arg) < 256 && pb_membersize(Instruction, arguments.sweep_arg) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Options_HourlyStats_MachineStatistics_Statistics_DrinkStatistics_Recipe_CoffeeParameters_BeanInfo_OptionParameters_DrinkTuneList_MilkParameters_FlavorParameters_PressureLUTVal_PressureLUT_SetValveArg_LoopArg_WaitForArg_GrinderArg_PumpArg_PistonPwmArg_SweepArg_Instruction_NutritionInfo)
#endif


/* @@protoc_insertion_point(eof) */
