/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Mon Aug 12 12:04:02 2019. */

#include "XpressHw.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t XpressHWStatus_fields[6] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, XpressHWStatus, valve, valve, &XpressValveStatus_fields),
    PB_FIELD(  2, MESSAGE , SINGULAR, STATIC  , OTHER, XpressHWStatus, switches, valve, &XpressSwitchStatus_fields),
    PB_FIELD(  3, MESSAGE , SINGULAR, STATIC  , OTHER, XpressHWStatus, temp, switches, &XpressTempStatus_fields),
    PB_FIELD(  4, MESSAGE , SINGULAR, STATIC  , OTHER, XpressHWStatus, pump, temp, &XpressPumpStatus_fields),
    PB_FIELD(  5, UINT32  , SINGULAR, STATIC  , OTHER, XpressHWStatus, unix_time, pump, 0),
    PB_LAST_FIELD
};

const pb_field_t XpressValveStatus_fields[10] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, XpressValveStatus, valve_center_steam_open, valve_center_steam_open, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, XpressValveStatus, valve_left_steam_open, valve_center_steam_open, 0),
    PB_FIELD(  3, BOOL    , SINGULAR, STATIC  , OTHER, XpressValveStatus, valve_right_steam_open, valve_left_steam_open, 0),
    PB_FIELD(  4, BOOL    , SINGULAR, STATIC  , OTHER, XpressValveStatus, valve_steam_fill_open, valve_right_steam_open, 0),
    PB_FIELD(  5, BOOL    , SINGULAR, STATIC  , OTHER, XpressValveStatus, valve_steam_purge_open, valve_steam_fill_open, 0),
    PB_FIELD(  6, BOOL    , SINGULAR, STATIC  , OTHER, XpressValveStatus, valve_milk_open, valve_steam_purge_open, 0),
    PB_FIELD(  7, BOOL    , SINGULAR, STATIC  , OTHER, XpressValveStatus, valve_alt_milk_open, valve_milk_open, 0),
    PB_FIELD(  8, BOOL    , SINGULAR, STATIC  , OTHER, XpressValveStatus, valve_latte_air_open, valve_alt_milk_open, 0),
    PB_FIELD(  9, BOOL    , SINGULAR, STATIC  , OTHER, XpressValveStatus, valve_latte_cap_open, valve_latte_air_open, 0),
    PB_LAST_FIELD
};

const pb_field_t XpressSwitchStatus_fields[5] = {
    PB_FIELD(  1, BOOL    , SINGULAR, STATIC  , FIRST, XpressSwitchStatus, switch_left_panel_open, switch_left_panel_open, 0),
    PB_FIELD(  2, BOOL    , SINGULAR, STATIC  , OTHER, XpressSwitchStatus, switch_upper_steam_wet, switch_left_panel_open, 0),
    PB_FIELD(  3, BOOL    , SINGULAR, STATIC  , OTHER, XpressSwitchStatus, switch_lower_steam_wet, switch_upper_steam_wet, 0),
    PB_FIELD(  4, BOOL    , SINGULAR, STATIC  , OTHER, XpressSwitchStatus, switch_steam_temp_high_limit, switch_lower_steam_wet, 0),
    PB_LAST_FIELD
};

const pb_field_t XpressTempStatus_fields[6] = {
    PB_FIELD(  1, FLOAT   , SINGULAR, STATIC  , FIRST, XpressTempStatus, steam_tank_temp_c, steam_tank_temp_c, 0),
    PB_FIELD(  2, FLOAT   , SINGULAR, STATIC  , OTHER, XpressTempStatus, steam_wand_temp_c, steam_tank_temp_c, 0),
    PB_FIELD(  3, FLOAT   , SINGULAR, STATIC  , OTHER, XpressTempStatus, refer_inside_temp_c, steam_wand_temp_c, 0),
    PB_FIELD(  4, FLOAT   , SINGULAR, STATIC  , OTHER, XpressTempStatus, refer_cold_sink_temp_c, refer_inside_temp_c, 0),
    PB_FIELD(  5, FLOAT   , SINGULAR, STATIC  , OTHER, XpressTempStatus, refer_hot_sink_temp_c, refer_cold_sink_temp_c, 0),
    PB_LAST_FIELD
};

const pb_field_t XpressPumpStatus_fields[10] = {
    PB_FIELD(  1, FLOAT   , SINGULAR, STATIC  , FIRST, XpressPumpStatus, milk_front_pump_ma, milk_front_pump_ma, 0),
    PB_FIELD(  2, FLOAT   , SINGULAR, STATIC  , OTHER, XpressPumpStatus, milk_rear_pump_ma, milk_front_pump_ma, 0),
    PB_FIELD(  3, FLOAT   , SINGULAR, STATIC  , OTHER, XpressPumpStatus, syrup_pump_1_ma, milk_rear_pump_ma, 0),
    PB_FIELD(  4, FLOAT   , SINGULAR, STATIC  , OTHER, XpressPumpStatus, syrup_pump_2_ma, syrup_pump_1_ma, 0),
    PB_FIELD(  5, FLOAT   , SINGULAR, STATIC  , OTHER, XpressPumpStatus, syrup_pump_3_ma, syrup_pump_2_ma, 0),
    PB_FIELD(  6, FLOAT   , SINGULAR, STATIC  , OTHER, XpressPumpStatus, syrup_pump_4_ma, syrup_pump_3_ma, 0),
    PB_FIELD(  7, FLOAT   , SINGULAR, STATIC  , OTHER, XpressPumpStatus, syrup_pump_5_ma, syrup_pump_4_ma, 0),
    PB_FIELD(  8, FLOAT   , SINGULAR, STATIC  , OTHER, XpressPumpStatus, syrup_pump_6_ma, syrup_pump_5_ma, 0),
    PB_FIELD(  9, FLOAT   , SINGULAR, STATIC  , OTHER, XpressPumpStatus, syrup_pump_7_ma, syrup_pump_6_ma, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(XpressHWStatus, valve) < 65536 && pb_membersize(XpressHWStatus, switches) < 65536 && pb_membersize(XpressHWStatus, temp) < 65536 && pb_membersize(XpressHWStatus, pump) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_XpressHWStatus_XpressValveStatus_XpressSwitchStatus_XpressTempStatus_XpressPumpStatus)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(XpressHWStatus, valve) < 256 && pb_membersize(XpressHWStatus, switches) < 256 && pb_membersize(XpressHWStatus, temp) < 256 && pb_membersize(XpressHWStatus, pump) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_XpressHWStatus_XpressValveStatus_XpressSwitchStatus_XpressTempStatus_XpressPumpStatus)
#endif


/* @@protoc_insertion_point(eof) */
